sudo: false
language: node_js
os: linux
node_js:
  - "12"
branches:
  only:
  - master
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: npm install
script:
  - npm run build
  - npm run test
after_success:
 
